In [1]:
import numpy as np

## numpy arrays

In [6]:
benimListem=[10,20,30]

In [7]:
type(benimListem)

list

In [8]:
np.array(benimListem)

array([10, 20, 30])

In [9]:
matrisListe=[[10,20,30],[40,50,60],[70,8,90]]

In [10]:
matrisListe[1][0]

40

In [11]:
np.array(matrisListe)

array([[10, 20, 30],
       [40, 50, 60],
       [70,  8, 90]])

## arange

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [19]:
np.linspace(0,10,8) ##sıfır ile 10 arasında bunlarda dahil 8 sayı üretir

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

## eye

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [21]:
np.random.randn(8)

array([ 2.0058092 , -0.82673503,  1.16929389,  0.66252641, -1.05046156,
        0.77327915,  0.11122932, -0.03395276])

In [22]:
np.random.randn(4,4)

array([[ 0.17789392, -1.21347472,  1.21299948, -0.50784051],
       [-0.2331666 , -1.53325542,  0.2823897 ,  0.38107087],
       [-0.12882077, -0.46831852,  1.15274712,  0.91300271],
       [ 0.19750431, -0.33512266, -0.99272453, -1.8442594 ]])

In [23]:
np.random.randint(1,10)

4

In [24]:
np.random.randint(1,100,7)

array([25, 27,  7, 89, 27, 95, 76])

In [25]:
benimNumpyDizim=np.arange(0,20)

In [26]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
benimRandomDizim=np.random.randint(0,100,30)

In [28]:
benimRandomDizim

array([82, 50, 28, 79, 92, 53, 68, 81, 54,  0, 97, 24, 29, 21, 35,  4, 65,
       57, 12, 44, 64, 22, 33, 82, 74, 12, 73, 75, 48, 15])

## numpy dizi metodları

In [29]:
benimNumpyDizim.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
benimNumpyDizim.max()

19

In [31]:
benimRandomDizim.max()

97

In [32]:
benimRandomDizim.min()

0

In [33]:
benimRandomDizim.argmax()

10

In [34]:
benimRandomDizim.argmin()

9

In [35]:
reshapeDizim=benimNumpyDizim.reshape(4,5)

In [36]:
reshapeDizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
reshapeDizim.shape

(4, 5)

In [39]:
reshapeDizim.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])