In [2]:
import numpy as np

In [5]:
np.arange(2,10,5)

array([2, 7])

In [6]:
benimDizi=np.arange(0,15)

In [7]:
benimDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
benimDizi[5:9]

array([5, 6, 7, 8])

In [16]:
benimDizi[12:14]=1000

In [17]:
benimDizi

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11, 1000, 1000, 1000])

In [18]:
baskaDizi=benimDizi[5:9]

In [19]:
baskaDizi

array([5, 6, 7, 8])

In [20]:
benimDizi

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11, 1000, 1000, 1000])

In [21]:
baskaDizi[1]=-1000

In [22]:
baskaDizi

array([    5, -1000,     7,     8])

In [23]:
benimDizi

array([    0,     1,     2,     3,     4,     5, -1000,     7,     8,
           9,    10,    11,  1000,  1000,  1000])

In [24]:
baskaDizi[:]=-999

In [26]:
baskaDizi

array([-999, -999, -999, -999])

In [27]:
benimDizi

array([   0,    1,    2,    3,    4, -999, -999, -999, -999,    9,   10,
         11, 1000, 1000, 1000])

In [32]:
ornekDizi=np.arange(0,20)

In [33]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
ornekDiziKopyasi=ornekDizi.copy()

In [35]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
ornekDiziKopyasislicing=ornekDiziKopyasi[7:13]

In [37]:
ornekDiziKopyasislicing

array([ 7,  8,  9, 10, 11, 12])

In [38]:
ornekDiziKopyasislicing[:]=-666

In [39]:
ornekDiziKopyasislicing

array([-666, -666, -666, -666, -666, -666])

In [40]:
ornekDiziKopyasi

array([   0,    1,    2,    3,    4,    5,    6, -666, -666, -666, -666,
       -666, -666,   13,   14,   15,   16,   17,   18,   19])

In [41]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Matrix

In [42]:
liste=[[10,20,30],[40,50,60],[70,80,90]]

In [43]:
matrisListem=np.array(liste)

In [44]:
matrisListem

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [49]:
matrisListem[1,1]

50

In [51]:
matrisListem[1:,1]

array([50, 80])

In [47]:
matrisListem[1:,1:]

array([[50, 60],
       [80, 90]])

In [52]:
matrisListem[2:,2:]

array([[90]])

In [53]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]

In [54]:
yeniMatrix=np.array(yeniListe)

In [55]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
yeniMatrix[1]

array([5, 6, 7, 8, 9])

In [60]:
yeniMatrix[[1,3]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [61]:
yeniMatrix[[3,0,1]]

array([[15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

## oprasyonlar

In [63]:
yeniBirDizi=np.random.randint(0,100,20)

In [64]:
yeniBirDizi

array([63, 33, 53, 22, 75, 11, 64, 17, 30, 28, 82, 30, 77, 14, 58, 39, 59,
       33, 29, 55])

In [65]:
yeniBirDizi>24

array([ True,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [66]:
sonuc=yeniBirDizi>24

In [67]:
sonuc

array([ True,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [68]:
yeniBirDizi[sonuc]

array([63, 33, 53, 75, 64, 30, 28, 82, 30, 77, 58, 39, 59, 33, 29, 55])

In [70]:
yeniBirDizi[yeniBirDizi>24]

array([63, 33, 53, 75, 64, 30, 28, 82, 30, 77, 58, 39, 59, 33, 29, 55])

In [71]:
sonDizi=np.arange(24)

In [72]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [74]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [77]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [79]:
sonDizi.max()

23

In [80]:
np.max(sonDizi)

23

In [81]:
np.argmax(sonDizi)

23